language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t brianrkleis/docker-r -f Dockerfile.dev .

script:
  - docker run -e CI=true brianrkleis/docker-r npm run test 
  
deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-sa-east-1-104991678107"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY