language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t brianrkleis/docker-r -f Dockerfile.dev .

script:
  - docker run -e CI=true brianrkleis/docker-r npm run test 